In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import spacy
from spacy import load
from spacy.lang.ru.examples import sentences
from spacy.lang.ru import Russian
import re
import nltk
from nltk.corpus import stopwords

In [3]:
stopwords_ru = stopwords.words('russian')

In [4]:
stopwords_ru

['и',
 'в',
 'во',
 'не',
 'что',
 'он',
 'на',
 'я',
 'с',
 'со',
 'как',
 'а',
 'то',
 'все',
 'она',
 'так',
 'его',
 'но',
 'да',
 'ты',
 'к',
 'у',
 'же',
 'вы',
 'за',
 'бы',
 'по',
 'только',
 'ее',
 'мне',
 'было',
 'вот',
 'от',
 'меня',
 'еще',
 'нет',
 'о',
 'из',
 'ему',
 'теперь',
 'когда',
 'даже',
 'ну',
 'вдруг',
 'ли',
 'если',
 'уже',
 'или',
 'ни',
 'быть',
 'был',
 'него',
 'до',
 'вас',
 'нибудь',
 'опять',
 'уж',
 'вам',
 'ведь',
 'там',
 'потом',
 'себя',
 'ничего',
 'ей',
 'может',
 'они',
 'тут',
 'где',
 'есть',
 'надо',
 'ней',
 'для',
 'мы',
 'тебя',
 'их',
 'чем',
 'была',
 'сам',
 'чтоб',
 'без',
 'будто',
 'чего',
 'раз',
 'тоже',
 'себе',
 'под',
 'будет',
 'ж',
 'тогда',
 'кто',
 'этот',
 'того',
 'потому',
 'этого',
 'какой',
 'совсем',
 'ним',
 'здесь',
 'этом',
 'один',
 'почти',
 'мой',
 'тем',
 'чтобы',
 'нее',
 'сейчас',
 'были',
 'куда',
 'зачем',
 'всех',
 'никогда',
 'можно',
 'при',
 'наконец',
 'два',
 'об',
 'другой',
 'хоть',
 'после',
 'на

In [5]:
doc = open('/Users/gleb/Documents/Dz_nlp.txt')
text = []

In [6]:
for str in doc:
    if str.strip():
        pattern = re.compile(r'\[(\d{2}:\d{2})\]')
        # print(pattern.match(str))
        if not pattern.match(str):
        # print(str)
            text.append(str)
            # print(text[-1].replace(r'[^\w\s]',' '))
            # text[-1].replace(r'[^\w\s]',' ').replace(r'\s+',' ')
            text[-1] = re.sub(r'[^\w\s]','',text[-1]).lower()

In [7]:
for str in text:
    print(str)

будет солнечно

солнечно до конца дня в красносельском районе как всегда ветер

сегодня будет солнечно ясное небо ни облачка не появится ночь чистая можно будет даже звёзды увидеть

температура опустится сразу на 67 градусов так что на улице днем будет не выше плюс 13 ощущение холода будут усиливать дожди которые начнутся в последний день этой недели и затем будут идти несколько суток

сегодня ясно без осадков атмосферное давление выше нормы

сегодня довольно теплая для сентября погода небо ясное и осадков не ожидается так что прогноз на сегодня очень приятный

в санктпетербурге сегодня ожидается 2018 c без осадков легкий ветер

трудно с ходу назвать фильм который породил столько же абсурдных пародий данное творение несмотря на свою трешовость снискал огромное количество поклонников

трагикомедия которая показывает последние дни двух молодых людей со смертельными диагнозами

фильм явно тянет на премию оскар проработанный сюжет очень красивая завораживающая картинка и я верю что он не у

In [8]:
nlp = Russian()
load_model = load('ru_core_news_sm')
lemma = []
for str in text:
    # print(str)
    new_str = []
    new_str = [token.lemma_ for token in load_model(str)]
    lemma.append(new_str[:-1])
    print(new_str[:-1])

['быть', 'солнечный']
['солнечный', 'до', 'конец', 'день', 'в', 'красносельский', 'район', 'как', 'всегда', 'ветер']
['сегодня', 'быть', 'солнечный', 'ясный', 'небо', 'ни', 'облачка', 'не', 'появиться', 'ночь', 'чистый', 'можно', 'быть', 'даже', 'звёзды', 'увидеть']
['температура', 'опуститься', 'сразу', 'на', '67', 'градус', 'так', 'что', 'на', 'улица', 'день', 'быть', 'не', 'высоко', 'плюс', '13', 'ощущение', 'холод', 'быть', 'усиливать', 'дождь', 'которые', 'начаться', 'в', 'последний', 'день', 'этот', 'неделя', 'и', 'затем', 'быть', 'идти', 'несколько', 'суток']
['сегодня', 'ясный', 'без', 'осадок', 'атмосферный', 'давление', 'высоко', 'норма']
['сегодня', 'довольно', 'тёплый', 'для', 'сентябрь', 'погода', 'небо', 'ясный', 'и', 'осадок', 'не', 'ожидаться', 'так', 'что', 'прогноз', 'на', 'сегодня', 'очень', 'приятный']
['в', 'санктпетербурге', 'сегодня', 'ожидаться', '2018', 'c', 'без', 'осадок', 'лёгкий', 'ветер']
['трудный', 'с', 'ходу', 'назвать', 'фильм', 'который', 'породить', 

In [9]:
lemma

[['быть', 'солнечный'],
 ['солнечный',
  'до',
  'конец',
  'день',
  'в',
  'красносельский',
  'район',
  'как',
  'всегда',
  'ветер'],
 ['сегодня',
  'быть',
  'солнечный',
  'ясный',
  'небо',
  'ни',
  'облачка',
  'не',
  'появиться',
  'ночь',
  'чистый',
  'можно',
  'быть',
  'даже',
  'звёзды',
  'увидеть'],
 ['температура',
  'опуститься',
  'сразу',
  'на',
  '67',
  'градус',
  'так',
  'что',
  'на',
  'улица',
  'день',
  'быть',
  'не',
  'высоко',
  'плюс',
  '13',
  'ощущение',
  'холод',
  'быть',
  'усиливать',
  'дождь',
  'которые',
  'начаться',
  'в',
  'последний',
  'день',
  'этот',
  'неделя',
  'и',
  'затем',
  'быть',
  'идти',
  'несколько',
  'суток'],
 ['сегодня',
  'ясный',
  'без',
  'осадок',
  'атмосферный',
  'давление',
  'высоко',
  'норма'],
 ['сегодня',
  'довольно',
  'тёплый',
  'для',
  'сентябрь',
  'погода',
  'небо',
  'ясный',
  'и',
  'осадок',
  'не',
  'ожидаться',
  'так',
  'что',
  'прогноз',
  'на',
  'сегодня',
  'очень',
  'пр

In [13]:
sents_all = []
for sents in lemma:
    sents = [gen_w for gen_w in sents if gen_w not in stopwords_ru]
    sents = ' '.join(sents)
    sents_all.append(sents)
    print(sents)

солнечный
солнечный конец день красносельский район ветер
сегодня солнечный ясный небо облачка появиться ночь чистый звёзды увидеть
температура опуститься сразу 67 градус улица день высоко плюс 13 ощущение холод усиливать дождь которые начаться последний день неделя затем идти несколько суток
сегодня ясный осадок атмосферный давление высоко норма
сегодня довольно тёплый сентябрь погода небо ясный осадок ожидаться прогноз сегодня очень приятный
санктпетербурге сегодня ожидаться 2018 c осадок лёгкий ветер
трудный ходу назвать фильм который породить столько абсурдный пародия данное творение несмотря свой трешовость снискал огромный количество поклонник
трагикомедия которая показывать последний день молодой человек смертельный диагноз
фильм явно тянуть премия оскар проработанный сюжет очень красивый завораживать картинка верить умереть конец фильм
ещё долго просмотр фильм друг повторять легендарный фраза главный герой водка внутри   снаружи бутылка ю вонна плей   лэтс плей забывать это дел

In [11]:
from spacy.lang.ru import Russian
import spacy

nlp = Russian()
load_model = spacy.load('ru_core_news_sm')
lemma1 = []
for sents in lemma:
    sents1 = [' '.join(sents)]
    # print(sents1)
    for str in sents1:
        doc = load_model(str)
        new_str = [token.lemma_ for token in doc if token.pos_ == "VERB"]
        lemma1.extend(new_str)

print(lemma1)

['солнечный', 'быть', 'появиться', 'увидеть', 'опуститься', 'усиливать', 'начаться', 'идти', 'ожидаться', 'ожидаться', 'назвать', 'породить', 'снискал', 'показывать', 'тянуть', 'завораживать', 'верить', 'умереть', 'повторять', 'забывать', 'делать', 'задавать']


In [14]:
sents_all

['солнечный',
 'солнечный конец день красносельский район ветер',
 'сегодня солнечный ясный небо облачка появиться ночь чистый звёзды увидеть',
 'температура опуститься сразу 67 градус улица день высоко плюс 13 ощущение холод усиливать дождь которые начаться последний день неделя затем идти несколько суток',
 'сегодня ясный осадок атмосферный давление высоко норма',
 'сегодня довольно тёплый сентябрь погода небо ясный осадок ожидаться прогноз сегодня очень приятный',
 'санктпетербурге сегодня ожидаться 2018 c осадок лёгкий ветер',
 'трудный ходу назвать фильм который породить столько абсурдный пародия данное творение несмотря свой трешовость снискал огромный количество поклонник',
 'трагикомедия которая показывать последний день молодой человек смертельный диагноз',
 'фильм явно тянуть премия оскар проработанный сюжет очень красивый завораживать картинка верить умереть конец фильм',
 'ещё долго просмотр фильм друг повторять легендарный фраза главный герой водка внутри   снаружи бутылка

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from scipy.spatial.distance import cosine,jaccard
from scipy.cluster.vq import kmeans,vq

In [95]:
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(sents_all)

k = 2

km_euc = KMeans(n_clusters=k, init='k-means++',random_state=42)
km_euc.fit(x)
label_euc = km_euc.labels_
silhouette_euc = silhouette_score(x,label_euc)

/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [96]:
silhouette_euc

0.027911548484398457

In [211]:
label_euc

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [207]:
def princ_cl(label_euc):
    for i in range(k):
        print(f'C_{i}')
        for j in range(label_euc.shape[0]):
            if label_euc[j] == i:
                print(sents_all[j])
princ_cl(label_euc)

C_0
температура опуститься сразу 67 градус улица день высоко плюс 13 ощущение холод усиливать дождь которые начаться последний день неделя затем идти несколько суток
сегодня ясный осадок атмосферный давление высоко норма
сегодня довольно тёплый сентябрь погода небо ясный осадок ожидаться прогноз сегодня очень приятный
санктпетербурге сегодня ожидаться 2018 c осадок лёгкий ветер
трудный ходу назвать фильм который породить столько абсурдный пародия данное творение несмотря свой трешовость снискал огромный количество поклонник
трагикомедия которая показывать последний день молодой человек смертельный диагноз
фильм явно тянуть премия оскар проработанный сюжет очень красивый завораживать картинка верить умереть конец фильм
ещё долго просмотр фильм друг повторять легендарный фраза главный герой водка внутри   снаружи бутылка ю вонна плей   лэтс плей забывать это делать губа бантик
ковёр действительно задавать весь стиль
C_1
солнечный
солнечный конец день красносельский район ветер
сегодня со

In [108]:
docs = sents_all[:2]

In [110]:
docs

['солнечный', 'солнечный конец день красносельский район ветер']

In [111]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer1 = CountVectorizer()
x1 = vectorizer1.fit_transform(docs)


In [118]:
from sklearn.metrics import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity

# Вычисление евклидового расстояния между документами
euclidean_distance_matrix = euclidean_distances(x1)

cosine_distance_matrix = cosine_similarity(x1)



In [120]:
euclidean_distance_matrix,cosine_distance_matrix

(array([[0.        , 2.23606798],
        [2.23606798, 0.        ]]),
 array([[1.        , 0.40824829],
        [0.40824829, 1.        ]]))

In [165]:
from sklearn.metrics import jaccard_score
def jac_score(x1):
    jaccard_matrix = np.zeros((x1.shape[0], x1.shape[0]))

# intersection = len(np.intersect1d(vector1, vector2))  # Пересечение уникальных элементов
# union = len(np.union1d(vector1, vector2))

    
    for i in range(x1.shape[0]):
        for j in range(i, x1.shape[0]):
            doc1 = np.array(x1[i].toarray())[0]
            # print(doc1)
            doc2 = np.array(x1[j].toarray())[0]
            # print(doc2)
            jaccard = jaccard_score(doc1, doc2, average='micro')
            jaccard_matrix[i, j] = jaccard
            jaccard_matrix[j, i] = jaccard
            print('jaccard',jaccard)
    return jaccard_matrix

print(jac_score(x1))

jaccard 1.0
jaccard 0.09090909090909091
jaccard 1.0
[[1.         0.09090909]
 [0.09090909 1.        ]]


In [157]:
np.array(x1[0].toarray())[0]

array([0, 0, 0, 0, 0, 1])

In [168]:
x1

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [130]:
vec_sen = vectorizer1.fit_transform(sents_all)

euclidean_sent = euclidean_distances(vec_sen)
cosine_sent = cosine_similarity(vec_sen)

In [167]:
euclidean_sent[:2],cosine_sent[:2]

(array([[0.        , 2.23606798, 3.        , 5.09901951, 2.82842712,
         4.        , 2.82842712, 4.35889894, 3.16227766, 4.24264069,
         5.09901951, 2.44948974],
        [2.23606798, 0.        , 3.74165739, 5.19615242, 3.60555128,
         4.58257569, 3.31662479, 4.89897949, 3.60555128, 4.58257569,
         5.56776436, 3.31662479]]),
 array([[1.        , 0.40824829, 0.31622777, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.40824829, 1.        , 0.12909944, 0.16329932, 0.        ,
         0.        , 0.15430335, 0.        , 0.13608276, 0.09901475,
         0.        , 0.        ]]))

In [200]:
jac_sent = jac_score(vec_sen)

jaccard 1.0
jaccard 0.9152542372881356
jaccard 0.8524590163934426
jaccard 0.6617647058823529
jaccard 0.8677685950413223
jaccard 0.7936507936507936
jaccard 0.8677685950413223
jaccard 0.7121212121212122
jaccard 0.8373983739837398
jaccard 0.765625
jaccard 0.6617647058823529
jaccard 0.8991596638655462
jaccard 1.0
jaccard 0.7795275590551181
jaccard 0.6142857142857143
jaccard 0.7936507936507936
jaccard 0.7251908396946565
jaccard 0.8225806451612904
jaccard 0.6496350364963503
jaccard 0.7936507936507936
jaccard 0.7251908396946565
jaccard 0.6028368794326241
jaccard 0.8225806451612904
jaccard 1.0
jaccard 0.5586206896551724
jaccard 0.7936507936507936
jaccard 0.7384615384615385
jaccard 0.765625
jaccard 0.6028368794326241
jaccard 0.7121212121212122
jaccard 0.6496350364963503
jaccard 0.5586206896551724
jaccard 0.765625
jaccard 1.0
jaccard 0.6142857142857143
jaccard 0.5374149659863946
jaccard 0.5915492957746479
jaccard 0.477124183006536
jaccard 0.6028368794326241
jaccard 0.5167785234899329
jaccard 0.4

In [212]:
jac_sent

array([[1.        , 0.91525424, 0.85245902, 0.66176471, 0.8677686 ,
        0.79365079, 0.8677686 , 0.71212121, 0.83739837, 0.765625  ,
        0.66176471, 0.89915966],
       [0.91525424, 1.        , 0.77952756, 0.61428571, 0.79365079,
        0.72519084, 0.82258065, 0.64963504, 0.79365079, 0.72519084,
        0.60283688, 0.82258065],
       [0.85245902, 0.77952756, 1.        , 0.55862069, 0.79365079,
        0.73846154, 0.765625  , 0.60283688, 0.71212121, 0.64963504,
        0.55862069, 0.765625  ],
       [0.66176471, 0.61428571, 0.55862069, 1.        , 0.61428571,
        0.53741497, 0.5915493 , 0.47712418, 0.60283688, 0.51677852,
        0.43949045, 0.61428571],
       [0.8677686 , 0.79365079, 0.79365079, 0.61428571, 1.        ,
        0.77952756, 0.83739837, 0.63768116, 0.75193798, 0.68656716,
        0.5915493 , 0.808     ],
       [0.79365079, 0.72519084, 0.73846154, 0.53741497, 0.77952756,
        1.        , 0.77952756, 0.58041958, 0.68656716, 0.64963504,
        0.53741497,

In [112]:
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances
from sklearn.feature_extraction.text import TfidfVectorizer



# Выбор метрики расстояния
distance_metric = "cosine"

# Расчет матрицы попарных расстояний между документами
pairwise_dist_matrix = pairwise_distances(x, metric=distance_metric)

pairwise_dist_matrix

array([[0.        , 0.64728581, 0.73749888, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.64728581, 0.        , 0.90741213, 0.88786624, 1.        ,
        1.        , 0.85397106, 1.        , 0.90719407, 0.9107952 ,
        1.        , 1.        ],
       [0.73749888, 0.90741213, 0.        , 1.        , 0.84457256,
        0.76854676, 0.93167762, 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 0.88786624, 1.        , 0.        , 0.93320015,
        1.        , 1.        , 1.        , 0.86275003, 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 0.84457256, 0.93320015, 0.        ,
        0.7317779 , 0.80871338, 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 0.76854676, 1.        , 0.7317779 ,
        0.        , 0.71514742, 1.        , 1.        , 0.942716  ,
        1.        ,

In [113]:
pairwise_dist_matrix.shape

(12, 12)

In [180]:
from pyclustering.cluster.kmeans import kmeans, kmeans_visualizer
from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer
from pyclustering.samples.definitions import FCPS_SAMPLES
from pyclustering.utils import read_sample

In [199]:
initial_centers = kmeans_plusplus_initializer(vec_sen.toarray().tolist(), 2).initialize()

AttributeError: module 'numpy' has no attribute 'warnings'

In [196]:
type(vec_sen.toarray().tolist())

list

In [205]:
km_euc = KMeans(n_clusters=k, init='k-means++',random_state=42)
km_cos = KMeans(n_clusters=k, init='k-means++',random_state=42)
km_jac = KMeans(n_clusters=k, init='k-means++',random_state=42)

In [206]:
km_euc.fit(euclidean_sent)
km_cos.fit(cosine_sent)
km_jac.fit(jac_sent)

/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=2, random_state=42)

In [208]:
princ_cl(km_euc.labels_)

C_0
температура опуститься сразу 67 градус улица день высоко плюс 13 ощущение холод усиливать дождь которые начаться последний день неделя затем идти несколько суток
трудный ходу назвать фильм который породить столько абсурдный пародия данное творение несмотря свой трешовость снискал огромный количество поклонник
фильм явно тянуть премия оскар проработанный сюжет очень красивый завораживать картинка верить умереть конец фильм
ещё долго просмотр фильм друг повторять легендарный фраза главный герой водка внутри   снаружи бутылка ю вонна плей   лэтс плей забывать это делать губа бантик
C_1
солнечный
солнечный конец день красносельский район ветер
сегодня солнечный ясный небо облачка появиться ночь чистый звёзды увидеть
сегодня ясный осадок атмосферный давление высоко норма
сегодня довольно тёплый сентябрь погода небо ясный осадок ожидаться прогноз сегодня очень приятный
санктпетербурге сегодня ожидаться 2018 c осадок лёгкий ветер
трагикомедия которая показывать последний день молодой чело

In [209]:
princ_cl(km_cos.labels_)

C_0
сегодня солнечный ясный небо облачка появиться ночь чистый звёзды увидеть
сегодня ясный осадок атмосферный давление высоко норма
сегодня довольно тёплый сентябрь погода небо ясный осадок ожидаться прогноз сегодня очень приятный
санктпетербурге сегодня ожидаться 2018 c осадок лёгкий ветер
C_1
солнечный
солнечный конец день красносельский район ветер
температура опуститься сразу 67 градус улица день высоко плюс 13 ощущение холод усиливать дождь которые начаться последний день неделя затем идти несколько суток
трудный ходу назвать фильм который породить столько абсурдный пародия данное творение несмотря свой трешовость снискал огромный количество поклонник
трагикомедия которая показывать последний день молодой человек смертельный диагноз
фильм явно тянуть премия оскар проработанный сюжет очень красивый завораживать картинка верить умереть конец фильм
ещё долго просмотр фильм друг повторять легендарный фраза главный герой водка внутри   снаружи бутылка ю вонна плей   лэтс плей забывать

In [210]:
princ_cl(km_jac.labels_)

C_0
температура опуститься сразу 67 градус улица день высоко плюс 13 ощущение холод усиливать дождь которые начаться последний день неделя затем идти несколько суток
трудный ходу назвать фильм который породить столько абсурдный пародия данное творение несмотря свой трешовость снискал огромный количество поклонник
ещё долго просмотр фильм друг повторять легендарный фраза главный герой водка внутри   снаружи бутылка ю вонна плей   лэтс плей забывать это делать губа бантик
C_1
солнечный
солнечный конец день красносельский район ветер
сегодня солнечный ясный небо облачка появиться ночь чистый звёзды увидеть
сегодня ясный осадок атмосферный давление высоко норма
сегодня довольно тёплый сентябрь погода небо ясный осадок ожидаться прогноз сегодня очень приятный
санктпетербурге сегодня ожидаться 2018 c осадок лёгкий ветер
трагикомедия которая показывать последний день молодой человек смертельный диагноз
фильм явно тянуть премия оскар проработанный сюжет очень красивый завораживать картинка вер

In [219]:
len(sents_all)

12

In [220]:
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score
# ari = adjusted_rand_score(true_labels, kmeans.labels_)
# nmi = normalized_mutual_info_score(true_labels, kmeans.labels_)

real_label = [0,0,0,0,0,0,0,1,1,1,1,1]

In [225]:
ari = adjusted_rand_score(real_label, km_cos.labels_)
nmi = normalized_mutual_info_score(real_label, km_cos.labels_)
ari,nmi

(0.18331805682859761, 0.36201225441690177)

In [223]:
km_cos.labels_

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int32)

In [243]:
sents_all

['солнечный',
 'солнечный конец день красносельский район ветер',
 'сегодня солнечный ясный небо облачка появиться ночь чистый звёзды увидеть',
 'температура опуститься сразу 67 градус улица день высоко плюс 13 ощущение холод усиливать дождь которые начаться последний день неделя затем идти несколько суток',
 'сегодня ясный осадок атмосферный давление высоко норма',
 'сегодня довольно тёплый сентябрь погода небо ясный осадок ожидаться прогноз сегодня очень приятный',
 'санктпетербурге сегодня ожидаться 2018 c осадок лёгкий ветер',
 'трудный ходу назвать фильм который породить столько абсурдный пародия данное творение несмотря свой трешовость снискал огромный количество поклонник',
 'трагикомедия которая показывать последний день молодой человек смертельный диагноз',
 'фильм явно тянуть премия оскар проработанный сюжет очень красивый завораживать картинка верить умереть конец фильм',
 'ещё долго просмотр фильм друг повторять легендарный фраза главный герой водка внутри   снаружи бутылка

In [275]:

def Kmeans_iter(euclidean_sent,cosine_sent,jac_sent,real_label=real_label,k=2):
    core = 42
    jac_sc = []
    euc_sc = []
    cos_sc = []
    for i in range(100):
        km_euc = KMeans(n_clusters=k, init='k-means++',random_state=core)
        km_cos = KMeans(n_clusters=k, init='k-means++',random_state=core)
        km_jac = KMeans(n_clusters=k, init='k-means++',random_state=core)
        
        km_euc.fit(euclidean_sent)
        km_cos.fit(cosine_sent)
        km_jac.fit(jac_sent)
        # print(km_euc.labels_)
        jac_sc.append(normalized_mutual_info_score(real_label, km_jac.labels_))
        euc_sc.append(normalized_mutual_info_score(real_label, km_euc.labels_))
        cos_sc.append(normalized_mutual_info_score(real_label, km_cos.labels_))
        core += 3
    return euc_sc,cos_sc,jac_sc



In [270]:
nlp = Russian()
load_model = spacy.load('ru_core_news_sm')
Noun_only = []
for sent in sents_all:
    # print(sent)
    doc = load_model(sent)
    new_str = [token.lemma_ for token in doc if token.pos_ == "NOUN"]
    # print(new_str)
    Noun_only.append(' '.join(new_str))

In [271]:
Noun_only

['',
 'конец день район ветер',
 'небо облачка ночь звёзды',
 'температура градус улица день ощущение холод дождь день неделя суток',
 'осадок давление норма',
 'сентябрь погода небо осадок прогноз',
 'санктпетербурге осадка ветер',
 'ходу фильм пародия творение трешовость количество поклонник',
 'трагикомедия день человек диагноз',
 'фильм премия сюжет картинка конец фильм',
 'просмотр фильм друг фраза герой водка бутылка лэтс плей губа бантик',
 'стиль']

In [272]:
Noun_only_vec = vectorizer1.fit_transform(Noun_only)

In [273]:
Noun_euc_sent = euclidean_distances(Noun_only_vec)
Noun_cosine_sent = cosine_similarity(Noun_only_vec)
Noun_jac_sent = jac_score(Noun_only_vec)

jaccard 1.0
jaccard 0.8461538461538461
jaccard 0.8461538461538461
jaccard 0.6842105263157895
jaccard 0.8823529411764706
jaccard 0.8113207547169812
jaccard 0.8823529411764706
jaccard 0.7454545454545455
jaccard 0.8461538461538461
jaccard 0.8113207547169812
jaccard 0.6271186440677966
jaccard 0.9591836734693877
jaccard 1.0
jaccard 0.7142857142857143
jaccard 0.6
jaccard 0.7454545454545455
jaccard 0.6842105263157895
jaccard 0.8113207547169812
jaccard 0.6271186440677966
jaccard 0.7777777777777778
jaccard 0.7454545454545455
jaccard 0.5238095238095238
jaccard 0.8113207547169812
jaccard 1.0
jaccard 0.5737704918032787
jaccard 0.7454545454545455
jaccard 0.7454545454545455
jaccard 0.7454545454545455
jaccard 0.6271186440677966
jaccard 0.7142857142857143
jaccard 0.6842105263157895
jaccard 0.5238095238095238
jaccard 0.8113207547169812
jaccard 1.0
jaccard 0.6
jaccard 0.5483870967741935
jaccard 0.6
jaccard 0.5
jaccard 0.6
jaccard 0.5483870967741935
jaccard 0.4117647058823529
jaccard 0.6551724137931034
j

In [276]:
Kmeans_iter(Noun_euc_sent,Noun_cosine_sent,Noun_jac_sent)

/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412:

([0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.1776354

In [277]:
Noun_and_Verb = []
for sent in sents_all:
    # print(sent)
    doc = load_model(sent)
    new_str = [token.lemma_ for token in doc if token.pos_ == "NOUN" or token.pos_ == "VERB"]
    # print(new_str)
    Noun_and_Verb.append(' '.join(new_str))

In [278]:
Noun_and_Verb

['солнечный',
 'конец день район ветер',
 'солнечный небо облачка появиться ночь звёзды увидеть',
 'температура опуститься градус улица день ощущение холод усиливать дождь начаться день неделя идти суток',
 'осадок давление норма',
 'сентябрь погода небо осадок ожидаться прогноз',
 'санктпетербурге ожидаться осадка ветер',
 'ходу назвать фильм породить пародия творение трешовость снискал количество поклонник',
 'трагикомедия показывать день человек диагноз',
 'фильм тянуть премия сюжет завораживать картинка верить умереть конец фильм',
 'просмотр фильм друг повторять фраза герой водка бутылка лэтс плей забывать делать губа бантик',
 'задавать стиль']

In [279]:
Noun_and_Verb_vec = vectorizer1.fit_transform(Noun_and_Verb)

In [280]:
Noun_and_Verb_euc_sent = euclidean_distances(Noun_and_Verb_vec)
Noun_and_Verb_cosine_sent = cosine_similarity(Noun_and_Verb_vec)
Noun_and_Verb_jac_sent = jac_score(Noun_and_Verb_vec)

jaccard 1.0
jaccard 0.863013698630137
jaccard 0.8378378378378378
jaccard 0.6585365853658537
jaccard 0.8888888888888888
jaccard 0.8133333333333334
jaccard 0.863013698630137
jaccard 0.7215189873417721
jaccard 0.8378378378378378
jaccard 0.7435897435897436
jaccard 0.6385542168674698
jaccard 0.9154929577464789
jaccard 1.0
jaccard 0.7215189873417721
jaccard 0.6190476190476191
jaccard 0.8133333333333334
jaccard 0.7435897435897436
jaccard 0.8378378378378378
jaccard 0.6585365853658537
jaccard 0.8133333333333334
jaccard 0.7215189873417721
jaccard 0.5813953488372093
jaccard 0.8378378378378378
jaccard 1.0
jaccard 0.5454545454545454
jaccard 0.7435897435897436
jaccard 0.7215189873417721
jaccard 0.7215189873417721
jaccard 0.6
jaccard 0.7
jaccard 0.6190476190476191
jaccard 0.5280898876404494
jaccard 0.7662337662337663
jaccard 1.0
jaccard 0.6190476190476191
jaccard 0.5632183908045977
jaccard 0.6
jaccard 0.4945054945054945
jaccard 0.6
jaccard 0.5111111111111111
jaccard 0.43157894736842106
jaccard 0.6385

In [281]:
Kmeans_iter(Noun_and_Verb_euc_sent,Noun_and_Verb_cosine_sent,Noun_and_Verb_jac_sent)

/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/gleb/miniforge3/envs/tensorflow/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412:

([0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.17763542004473515,
  0.1776354